package com.automart;

import com.sun.net.httpserver.Headers;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;

import java.io.IOException;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.InetSocketAddress;
import java.net.URI;
import java.net.URL;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.UUID;
import java.util.regex.Pattern;
import java.util.concurrent.Executors;


import static com.automart.AutoMartApplication.*;

final class Settings {
    String fullName = "Auto Mart Manager";
    String profilePhoto = "";
    String premiumBadgeStatus = "Verified seller";
    String teamEmail = "team.automart@gmail.com";
    String phone = "+94 77 123 4567";
    String location = "Colombo, Western Province";
    String bio = "Trusted marketplace operator focused on premium listings, quick communication, and buyer confidence.";
    String defaultCity = "Colombo 03";
    String workspaceMode = "operations";
    String defaultDashboard = "settings";
    String notificationFrequency = "Immediate";
    String preferredContact = "WhatsApp";
    String theme = "Dark";
    String distanceUnit = "Kilometers";
    String currency = "LKR";
    String preferredLocationFirst = "Colombo";
    String defaultPickup = "Rajagiriya vehicle yard";
    String businessHours = "Mon-Sat • 9:00 AM - 6:00 PM";
    String awayMessage = "Thanks for your message. We will reply shortly.";
    String blockedUsers = "";
    String subscriptionPlan = "Premium Dealer";
    String featuredCredits = "12";
    String billingEmail = "billing.automart@gmail.com";
    String dealerName = "Auto Mart Premium Dealer";
    String whatsappNumber = "+94 77 222 3344";
    String registrationNumber = "PV 123456";
    String businessAddress = "No. 45, Colombo 05";
    String sellerType = "dealer";
    String mapsUrl = "";
    String warrantyNote = "3-month engine & gearbox warranty";
    String financePartner = "BOC / Commercial Bank";
    String tradeInPolicy = "Trade-ins accepted after valuation";
    String responseSla = "Within 15 minutes";
    String wishlistSpotlight = "Premium German sedans";
    String priceType = "Fixed";
    String listingDuration = "30 Days";
    String minPhotos = "8";
    String deliveryFee = "LKR 12,500";
    String testDriveSlot = "45 minutes";
    String paymentMethod = "Bank Transfer";
    String bankName = "Bank of Ceylon";
    String accountName = "Auto Mart Pvt Ltd";
    String accountNumber = "1234567890";
    String welcomeHeadline = "Sell smarter on Auto Mart";
    String welcomeSubtext = "Trusted used-car buying and selling in Sri Lanka";
    String defaultSignupRole = "seller";
    String planNote = "Premium Dealer plan active";
    boolean verifiedSeller = true;
    boolean smsAlerts = true;
    boolean pushAlerts = true;
    boolean priceDropAlerts = true;
    boolean savedSearchAlerts = true;
    boolean chatNotifications = true;
    boolean emailNotifications = true;
    boolean conciergeMode = true;
    boolean inventorySync = true;
    boolean twoFactorAuth = true;
    boolean privacyMode = false;
    boolean sessionShield = true;
    boolean showPhoneNumber = false;
    boolean governmentIdUploaded = true;
    boolean dataExportReady = true;
    boolean autoRenew = true;
    boolean hidePhone = true;
    boolean automatedReplies = true;
    boolean googleVehicleAds = false;
    boolean dmsSync = false;
    boolean featuredBoost = true;
    boolean inspectionAvailable = true;
    boolean serviceHistoryEnabled = true;
    boolean vinEnabled = true;
    boolean financeAvailable = true;
    boolean tradeInEnabled = true;
    boolean warrantyEnabled = true;
    boolean documentVerification = true;
    boolean accidentHistoryEnabled = true;
    boolean islandwideDelivery = true;
    boolean homeTestDrive = false;
    boolean previousOwnersEnabled = true;
    boolean allowEmailLogin = true;
    boolean socialGoogle = true;
    boolean socialFacebook = true;
    boolean socialLinkedin = true;
    boolean socialSignup = true;
    boolean animatedAuth = true;
}
